exclude: ["README.md", "vendor", "Gemfile", "Gemfile.lock"]

title: satanic0258-github-io
permalink: none

bootstrap-version: "3.3.7" # Bootstrap http://getbootstrap.com/getting-started/
jquery-version: "3.2.1" # jQuery https://jquery.com/download/

include: ["snippets", "memos"]

collections :
  snippets    :
    output    : true
    permalink : /:collection/:path.html
  memos       :
    output    : true
    permalink : /:collection/:path.html